services:
  igem_mc:
    build: minecraft
    image: thelostlambda/minecraft:latest
    container_name: igem_mc
    restart: on-failure
    network_mode: host
    volumes:
      - ~/Minecraft/iGEM:/root/config
    cap_add:
      - ALL

  squidgate:
    build: squidgate
    image: thelostlambda/squidgate:latest
    container_name: squidgate
    restart: on-failure
    network_mode: host
    volumes:
      - ~/.ssh:/home/forward/.ssh:ro
